from os import getenv

from langchain.agents import AgentType, initialize_agent
from langchain.chat_models import ChatOpenAI

from tester.tools import tools

llm = ChatOpenAI(model_name="gpt-4", request_timeout=120)  # type: ignore

agent = initialize_agent(
    tools, llm, agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True
)


agent.run(
    """
1. read file called `stressable/utils.py`
2. show project structure
3. use pytest, write to file called `tests/test_utils.py` with unit tests for `stressable/utils.py`
4. run tests
5. if tests are passing go to next step, otherwise go to step 3
6. create a new branch with autogenerated name
7. commit changes with autogenerated commit message
8. push changes
9. create a pull request with autogenerated title
"""
)
